# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Allective' do


pod 'Fabric'
pod 'Crashlytics'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'UIView+Shake'
pod 'Google/Analytics'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'AlamofireImage'
pod 'NotificationBannerSwift'
pod 'SnapKit', '= 3.2.0'
pod 'youtube-ios-player-helper', '~> 0.1.4'
pod 'AKImageCropperView'
pod 'AuthorizeNetAccept', '~> 0.1.0'
use_frameworks! //
end


target 'AllectiveTests' do
end

target 'AllectiveUITests' do
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = “3.2”
        end
    end
end
